package com.pendulum.phone.db

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * The database.
 *
 * ### `fallbackToDestructiveMigration` is forbidden here, and this is not a matter of style
 *
 * The call appears nowhere and must never appear. The reason lies in the nature of what is stored:
 * the derived tables (`sleep_window`, `clm_event`, `plm_result`) are rebuilt by replaying the
 * analysis, but `night_session`, `chunk`, `night_context`, `hc_snapshot` and
 * `questionnaire_response` are not rebuilt — they are the only traces of nights that happened
 * once. And **the algorithm will change**: that is the only postulate this project can count on.
 * The day it changes, the value of the past campaign lies entirely in the possibility of rescoring
 * it from the raw data. A destructive migration turns that campaign into nothing, silently, at the
 * first installation of a version whose schema number has moved.
 *
 * In practice: every evolution goes through an explicit `Migration` passed to `addMigrations`, and
 * the schema is exported into `phone/schemas/` (`room.schemaLocation`) so that the migration is
 * verifiable rather than taken on trust. `exportSchema = true` stays true **even now that the
 * database is at v1 and there is not a single migration left**: it is today's export that will
 * make tomorrow's migration verifiable, and it cannot be produced after the fact.
 *
 * ### The version went back to 1 on 7 August 2026, and the four migrations were removed
 *
 * The database carried `version = 5` and four migrations (1 -> 2, 2 -> 3, 3 -> 4, 4 -> 5). None of
 * them ever ran anywhere other than on the development device: **the application has been
 * installed on nobody's phone**, there is no database to migrate, anywhere. Four migrations that
 * recount the hesitations of the schema are paid for at every re-reading and above all at every
 * subsequent migration — each one is one more path to keep correct — without protecting a single
 * piece of data. The first real installation will therefore create a v1 database, which is today's
 * shape.
 *
 * What was removed, summarised here so that nobody has to dig through the history:
 *
 *  - **v1 -> v2**: `night_context` stops being keyed by `sessionHex` and is keyed by the night key
 *    (`YYYY-MM-DD`, rolling over at noon); `night_session` gains the same column and its index.
 *    The defect fixed: the sealing **precedes** the night, so at the time of the evening form there
 *    was no `sessionHex` to write, and guard rail 1 was literally impossible to satisfy. The fixed
 *    shape is that of the current schema.
 *  - **v2 -> v3**: the `comparable_night` view exposes `rhythmValid`. The interface displayed
 *    `fundamentalSec` without knowing that `:algo` had refused the fit — a refusal returns a finite
 *    number, hence one indistinguishable from an accepted result.
 *  - **v3 -> v4**: creation of `telemetry_point`. The telemetry arrived in the `TLM!` block of the
 *    chunks and ingestion threw it away after checking the CRC.
 *  - **v4 -> v5**: removal of `respiratoryConfidence` from `plm_result`. The column carried a
 *    three-valued enum of which one value closed the publication gate, and nothing fed it: the
 *    value written was `MEDIUM`, hard-coded, for every night. A gate that has never closed is worse
 *    than an absent gate — it documents itself as a protection.
 *
 * Two rules born of those migrations **survive their removal**, because they will hold on the day
 * of the first real migration:
 *
 *  1. **A migration never loses a column of raw data.** Renaming, yes; copying into a fresh table,
 *     yes; deleting a column of `chunk`, of `telemetry_point` or of `night_context`, no — those are
 *     the only data that nothing allows to be reconstituted.
 *  2. **A view is recreated only when it is changed**, and when it is recreated it is built from
 *     [ComparableNightSql.SQL] with `trim()`. Room does not compare a view field by field: it
 *     compares its **text** with the normalised text its annotation processor generated. The
 *     literal starts with a line break and twelve spaces of indentation, and those thirteen
 *     characters were enough, on 3 August 2026, to make every already installed database
 *     impossible to open — `fallbackToDestructiveMigration` being absent, the exception travelled
 *     up to the first screen that read anything. The bench on real hardware saw it; the test suite
 *     did not.
 *
 * `MigrationTest` disappears along with the migrations: it no longer had a subject. What replaces
 * it is `ImmutabilityTest`, which covers a far more serious hole that nothing covered — the
 * triggers below. The exported schemas `2.json`, `3.json` and `4.json` are deleted; `1.json` is
 * regenerated by the compilation.
 *
 * ### The triggers
 *
 * Room does not model SQLite triggers. The ones that make `night_context` append-only are
 * therefore laid down by hand in [Callback.onCreate] **and** in [Callback.onOpen] (with
 * `IF NOT EXISTS`): `onCreate` alone would not be enough, a future migration recreating the table
 * would carry its triggers away without anything signalling it.
 */
@Database(
    entities = [
        NightSessionEntity::class,
        ChunkEntity::class,
        TelemetryPointEntity::class,
        SleepWindowEntity::class,
        ClmEventEntity::class,
        PlmResultEntity::class,
        NightContextEntity::class,
        HcSnapshotEntity::class,
        QuestionnaireResponseEntity::class,
        ParamProfileEntity::class,
    ],
    views = [ComparableNight::class],
    version = PendulumDatabase.VERSION,
    exportSchema = true,
)
abstract class PendulumDatabase : RoomDatabase() {

    abstract fun nightDao(): NightDao
    abstract fun chunkDao(): ChunkDao
    abstract fun telemetryDao(): TelemetryDao
    abstract fun derivedDao(): DerivedDao
    abstract fun contextDao(): ContextDao
    abstract fun hcSnapshotDao(): HcSnapshotDao
    abstract fun questionnaireDao(): QuestionnaireDao
    abstract fun paramDao(): ParamDao
    abstract fun trendDao(): TrendDao
    abstract fun maintenanceDao(): MaintenanceDao

    companion object {
        const val VERSION = 1
        const val NAME = "pendulum.db"

        @Volatile
        private var instance: PendulumDatabase? = null

        fun get(context: Context): PendulumDatabase = instance ?: synchronized(this) {
            instance ?: build(context.applicationContext).also { instance = it }
        }

        private fun build(context: Context): PendulumDatabase =
            Room.databaseBuilder(context, PendulumDatabase::class.java, NAME)
                // Foreign keys are NOT enabled by default in SQLite. Without this line,
                // `onDelete = CASCADE` is decorative and deleting a night would leave its chunks
                // and its results in the database, attached to nothing.
                .addCallback(Callback)
                // No `.addMigrations(...)`: the database is at v1 and no earlier version exists on
                // any device. The line will come back with the first migration.
                // Deliberately absent: .fallbackToDestructiveMigration()
                .build()

        /** For the instrumented tests, which must be able to start again from an empty database. */
        internal fun resetInstanceForTests() {
            instance = null
        }
    }

    private object Callback : RoomDatabase.Callback() {

        override fun onCreate(db: SupportSQLiteDatabase) {
            createTriggers(db)
        }

        override fun onOpen(db: SupportSQLiteDatabase) {
            db.execSQL("PRAGMA foreign_keys = ON")
            createTriggers(db)
        }
    }
}

/**
 * The triggers that make the evening context non-modifiable.
 *
 * The DAO exposes neither `@Update` nor `@Delete` — but a DAO can be modified in one line, and the
 * day someone (me, in six months, with a good reason) adds one, there will be no failure to remind
 * them. A trigger will: `RAISE(ABORT)` makes the transaction fail, and the message says why.
 *
 * This is guard rail 1 translated into SQL: the dose and the context are sealed **before** the
 * watch agrees to start, and the failure mode to prevent is not fraud, it is the good-faith
 * touch-up on waking, after seeing the figure.
 *
 * None of this is checked by Room, whose schema validation ignores triggers entirely: it is
 * `ImmutabilityTest` (an instrumented test) that asks the question, by attempting the forbidden
 * writes on the real database and by checking that after a normal opening the three triggers are
 * indeed in `sqlite_master`.
 */
private fun createTriggers(db: SupportSQLiteDatabase) {
    db.execSQL(
        """
        CREATE TRIGGER IF NOT EXISTS night_context_no_update
        BEFORE UPDATE ON night_context
        BEGIN
            SELECT RAISE(ABORT, 'night_context is sealed: no modification after the fact');
        END
        """.trimIndent()
    )
    db.execSQL(
        """
        CREATE TRIGGER IF NOT EXISTS night_context_no_delete
        BEFORE DELETE ON night_context
        BEGIN
            SELECT RAISE(ABORT, 'night_context is sealed: deletion forbidden (see eraseEverything)');
        END
        """.trimIndent()
    )
    db.execSQL(
        """
        CREATE TRIGGER IF NOT EXISTS hc_snapshot_no_update
        BEFORE UPDATE ON hc_snapshot
        BEGIN
            SELECT RAISE(ABORT, 'hc_snapshot is a log: a reading is added, it is not corrected');
        END
        """.trimIndent()
    )
}

/**
 * Total deletion, including the raw chunks.
 *
 * Three reasons not to settle for a `DELETE FROM night_session`:
 *  - the chunk files live on the disk, not in the database;
 *  - the append-only triggers refuse the `DELETE` on `night_context` and must be dropped and then
 *    put back, failing which the erasure only half succeeds;
 *  - `VACUUM` is necessary so that the freed pages do not stay readable in the database file.
 *    Without it, "erase everything" leaves the content recoverable in the free pages.
 *
 * The caller erases the files **before** calling this: see the KDoc of [MaintenanceDao].
 */
suspend fun PendulumDatabase.eraseEverything() {
    val db = openHelper.writableDatabase
    db.execSQL("DROP TRIGGER IF EXISTS night_context_no_update")
    db.execSQL("DROP TRIGGER IF EXISTS night_context_no_delete")
    db.execSQL("DROP TRIGGER IF EXISTS hc_snapshot_no_update")
    try {
        maintenanceDao().deleteAllSessions()
        maintenanceDao().deleteAllContexts()
        maintenanceDao().deleteAllQuestionnaires()
        maintenanceDao().deleteAllProfiles()
    } finally {
        createTriggers(db)
    }
    // Outside a transaction, and this is indispensable: VACUUM fails inside a transaction.
    db.execSQL("VACUUM")
}
